server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    fetch-registry: false #不从注册中心拉取注册表

spring:
  application:
    name: three-service
  datasource:
    url: jdbc:mysql://10.31.47.29:3306/exam?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true  #格式化sql
    hibernate:
      ddl-auto: update